### ISSUE TITLE
版权声明

### ISSUE THREAD

**Issue by Lloyd0577** [autumnqfeng/write_rpc#3]
你好，你的这篇博客：
http://autumn200.com/2019/03/16/UML-class-picture/
是全篇转载我的文章：
https://www.jianshu.com/p/2828874af134
请加上原地址出处谢谢！

**Comment by autumnqfeng** [comment]
你好，已经加上原文地址了，文章写的很好，收藏学习下

**Comment by autumnqfeng** [comment]
你好，已经加上文章原文地址了，文章写的不错，收藏下

**Comment by Lloyd0577** [comment]
好的 谢谢！
